version: "3.7"
services:
  booksearcher:
    image: blessingdocker/klva_nbs:latest
    deploy:
      replicas: 3
    container_name: book-searcher
    links:
      - nlp:nlp-server
    ports:
      - "8080:80"
  nlp:
    image: blessingdocker/klva_nlp:latest
    deploy:
      replicas: 2
    container_name: nlp-server